#include "hash_tables.h"

/**
 * key_index - This function computes the index at which a particular table
 * item will be stored
 * @key: The key generated by the hash function
 * @size: The size of the hash table
 * Return: The index of the hash table where the hash table item will be stored
 */
unsigned long int key_index(const unsigned char *key, unsigned long int size)
{
	unsigned long int i;

	i = hash_djb2(key);
	return (i % size);
}
